apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: "A new service"
  annotations:  
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: josefernandezceiba/${{ values.repoUrl }}
spec:
  type: service
  owner: user:guest
  lifecycle: experimental